version: "3"
services:
  exercise3:
    build: .
    ports:
     - "9003:9003"
     depends_on:
      - mongodb
    command: ["mongodb:27027","-t","5", "--","node", "app.js"]
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"